version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: tf-mongodb
    ports:
      - "27017:27017"
    volumes:
      - tf-mongo-data:/data/db

  backend:
    build: ./backend
    container_name: tf-backend
    ports:
      - "3500:3500"
    environment:
      - MONGO_CONN_STR=mongodb://mongodb:27017/tasks
      - PORT=3500
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: tf-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3500/api/tasks
    depends_on:
      - backend

volumes:
  tf-mongo-data:
